### ISSUE TITLE
Missing DWT input file

### ISSUE THREAD

**Issue by mrnakhkash** [iot-locus/kernels#2]
I compiled the DWT code successfully but when I executed it, there was a segmentation fault. when I reviewed the source code I saw that in line 21 the code wants reads run input file starting with "dwt_". but there isn't any input file for the DWT code. So I am, guessing the authors forgot to include them.

**Comment by iot-locus** [comment]
The project is mainly focusing on the performance/power evaluation. It would be too large to include all the input files in the repository. I suggest you to generate your own input files to test the performance. The DWT kernel only does computation on matrix, so it would be easier for you to generate multiple input file (dwt_1,2...) for different threads.

Best regards
